hash-format = "sha256"

[[files]]
file = "config/modrinth.index.json"
hash = "3e1434d567389cca96039f3ce98594837b54ad33480e8843ae162315eb760770"

[[files]]
file = "config/simple-modpack-update-checker.json"
hash = "44b2f2bebb1317f16e609fdd0b9f245d1d0a4abe5c1200a667cae34ad5867213"

[[files]]
file = "config/yosbr/config/aaron-mod.json"
hash = "42f5b7adf5cb1ab2598ea7920c5590ad64df4a3852792da5fb2a95e9304d421d"

[[files]]
file = "config/yosbr/config/chatpatches.json"
hash = "6c7324ce2fc05e0328640930fbd0cf42f6b5c5b20ea523f6a193559c4915e02a"

[[files]]
file = "config/yosbr/config/entityculling.json"
hash = "dc7598cff8d5128cabb1757c5e38a9cbf492ac2d195ed403bc47c679b4a1d4dc"

[[files]]
file = "config/yosbr/config/fabric/indigo-renderer.properties"
hash = "d1241397dbd8f3e664c94271bd9db41d9d2a9514f28a9e903df318897eec0874"

[[files]]
file = "config/yosbr/config/ferritecore.mixin.properties"
hash = "3cc3011619f098fda6ad213a7c4d1468802ff827591a5917c2b7bf3150bfb2ea"

[[files]]
file = "config/yosbr/config/gammautils.json"
hash = "2b38ec7a0663b3b85f296f305a5564cd5c5c16fc83ed8377ecf2c34f8c254efc"

[[files]]
file = "config/yosbr/config/immediatelyfast.json"
hash = "f4933d24a5acc79d5a54716d914ad499a49cb3083130fd994874d9efa686f580"

[[files]]
file = "config/yosbr/config/iris-excluded.json"
hash = "4d3264b58c502afaeca3f44e8d2db0843c54b8ba957afd21a2d450fe10dafefb"

[[files]]
file = "config/yosbr/config/iris.properties"
hash = "eac97b4ef2cad12ecda2de5808e0fccdc072e10f7a2785cb0751c5033a98b786"

[[files]]
file = "config/yosbr/config/lithium.properties"
hash = "6cf6f83720071fd1657c8e79b357caf68d40f410ae123e5f922483eb1d1d25be"

[[files]]
file = "config/yosbr/config/modelfix-client.json"
hash = "7e02c1d587a4c011b0b18080b7ba7451bd44535159a52c4c0c9a94b863334678"

[[files]]
file = "config/yosbr/config/modmenu.json"
hash = "de9f11d332bf2804986886e45e5235363910594e7b5311a7c887bda9b7cac90f"

[[files]]
file = "config/yosbr/config/roughlyenoughitems/collapsible.json5"
hash = "31e99198f7a93bbbb6cd9d005a4e90cb44eb5a73f74d7c17c01b0277485bf2c4"

[[files]]
file = "config/yosbr/config/roughlyenoughitems/config.json5"
hash = "2025bf43bbc7cbcc311011ace0462745485f4603e3357ecc0857bc773db7b7c8"

[[files]]
file = "config/yosbr/config/roughlyenoughitems/favorites.json5"
hash = "589c13e9ebbb9ae1b868d73be8c4e30323dcb03efacf59d75b9d614f1b069b47"

[[files]]
file = "config/yosbr/config/roughlyenoughitems/pinyin.properties"
hash = "abc1345cfe16da39cd506406bd895447673b25e9e837052e89d7c11b99f55f57"

[[files]]
file = "config/yosbr/config/roughlyenoughitems/pinyin_double.properties"
hash = "8a9b3e877222d06729dd594ebde05c4b26695be058833f8120f96d611d67da19"

[[files]]
file = "config/yosbr/config/skyblocker.json"
hash = "7ed1726b8d1a995b7cdde06812535960d3f410222d6dbe5e3a7499e461b3b641"

[[files]]
file = "config/yosbr/config/skyblocker/hud_widgets.json"
hash = "beb746240cfd56020f7631f539084c4f0ba049dd62e21ab9b953050d8d3f2c1f"

[[files]]
file = "config/yosbr/config/skyblocker/shortcuts.json"
hash = "3cd85c545316fea761bfa09318519a4851343d302b8bd1e4db0def81399cd4f9"

[[files]]
file = "config/yosbr/config/skyblocker/speed_presets.json"
hash = "22071932165fda8b52c768e2975eea60aa26542ac04e57a12873da65f4a01a32"

[[files]]
file = "config/yosbr/config/skyblocker/status_bars.json"
hash = "cf7b65aa826bd973b2a389f6afe94ca35b26d840b232c88aa833acd0d86b988a"

[[files]]
file = "config/yosbr/config/skyblocker/update_notifications.json"
hash = "d5785ecd0353396b2168bf5487f654e8cfcf998d23637e73a1ae0137a75130eb"

[[files]]
file = "config/yosbr/config/sodium-extra-options.json"
hash = "da6128463b44919a76c90f216f1ede49e4b052b7d6f6c98dddd9ba91f9c6ab24"

[[files]]
file = "config/yosbr/config/sodium-extra.properties"
hash = "a2f1b47c1eaa119ab34727f1d43c2506cb3d7f17ba8fb4efb49e20c8e0b58e70"

[[files]]
file = "config/yosbr/config/sodium-fingerprint.json"
hash = "a6a686b41ee84af7094051f2cebef4e1d322efd654fce32106d12ad8eba76d49"

[[files]]
file = "config/yosbr/config/sodium-mixins.properties"
hash = "b627c4456e6fa0bc4b5f85e2f1cd949faedae3cb9afdaf2a5f52e6f3b6ae1f01"

[[files]]
file = "config/yosbr/config/sodium-options.json"
hash = "445a55bccce87dd8467f3265d1572827e8778e873e3bb70290adf0bb8a811e96"

[[files]]
file = "config/yosbr/config/tooltipscroll.json"
hash = "0c3af65d5fe2cb919fb34e4a8c81337a77f232367b4e63c1ec29e3a74e3e44f2"

[[files]]
file = "config/yosbr/config/yacl.json5"
hash = "d26a63d3cdf326412ba86dcc2781060bc53ed6c74ac7808e65325452e264e820"

[[files]]
file = "config/yosbr/config/zoomify.json"
hash = "60a78fe1b271ce9b53e295235eb5a7cdb3a8692ca583fdaa7f5bc09f9049e2f4"

[[files]]
file = "config/yosbr/options.txt"
hash = "131b4b1d85fbd8f46ff55834eba6ff3c0d63ac5eee829d33baf3b0345971cfa5"

[[files]]
file = "mods/architectury-api.pw.toml"
hash = "02a609de09efd7cadb420e44e392d6b48d62ec92ffefcbef4af4511bc8b33ac2"
metafile = true

[[files]]
file = "mods/chatpatches.pw.toml"
hash = "50d199bba8e74b56a4111530eaf647eba4e450b64fb0e96b9f832067c2fbd3fe"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "7621c38bf5eb90cc7458a78eeab30088bae4bf9f29f72bbc2a2a7c37fc06b551"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "179914e2ec888ecc6f11275ef5125fe834eadf160f78d1647c0e6beb879bb35a"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "1943cee706f90e5e828de013387ee1d1ae9ec1ae6a63da767be9bfd64018b79a"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "94f000249d21c4fc3b7744f9579bb6ac0d48e6bf4860fad16f23c997950a47f3"
metafile = true

[[files]]
file = "mods/ferritecore-fabric.pw.toml"
hash = "3dcc43cbc807ec49377efe574b4670ee91e62474aee1bcd068495adea8bc1f6a"
metafile = true

[[files]]
file = "mods/gamma-utils.pw.toml"
hash = "1257abb95fac462c055f29dbf1db090c36b41d92dbd866aec86228d9d50114da"
metafile = true

[[files]]
file = "mods/immediatelyfast.pw.toml"
hash = "3617809c044fc866d3b064e0264aa4a302ff9bcaeff3ea04a9c1d53565cfc26c"
metafile = true

[[files]]
file = "mods/irisshaders.pw.toml"
hash = "d93b46b247fe2a2a3a70638c66fa73618d46cad43aeb7df0d90f5311ba2de280"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "6fd385ab7c8e30ff3fb79a941e5149b16e0a971e6feddbd5902f3cfc5e9aba4d"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "474dbec1a749b8a1af2504bf0380c77a3f5815ba4038614b91b873aae2fe57d8"
metafile = true

[[files]]
file = "mods/reeses-sodium-options.pw.toml"
hash = "56390b7b5a7815868460b7f489b8bafba913652bb10a9f8383cefba1a483a15f"
metafile = true

[[files]]
file = "mods/roughly-enough-items.pw.toml"
hash = "067338009da5e8f1552cc0dea032a02b6d96e9a94b8a6cea7b63fe5bbc52b97c"
metafile = true

[[files]]
file = "mods/skyblocker-modpack-lib-1.0.0.jar"
hash = "5972327b4f6d78d2bc8fc0696c7f0f2cd3a4c32e402d38c3c88996dece4338ef"

[[files]]
file = "mods/skyblocker.pw.toml"
hash = "eed9914f3933a17d4ab0124d3ea9520cc13f441d932a1372a4ac5cc248225c39"
metafile = true

[[files]]
file = "mods/smuc.pw.toml"
hash = "d98ee17724f0b807f04c1a4c7b86ff87417be9723a9c83ab921116088aa6d188"
metafile = true

[[files]]
file = "mods/sodium-extra.pw.toml"
hash = "ebe5f1bddd8a2fafb5d2565fee640568345bf132c49335232fb9653915ed11f4"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "e22254a6f9d2eb28da5e503e48faaf9f6767e6485f8607b449713a461e850d46"
metafile = true

[[files]]
file = "mods/text-placeholder-api.pw.toml"
hash = "5fd4069e0ce9dce787eaffdbdb1048a09a5be0e072d6a8a10d49152919e71444"
metafile = true

[[files]]
file = "mods/tooltip-scroll-fabric.pw.toml"
hash = "8cbfe7c05aa8a69a82d29f44a4672376457b94b98f11cfdcdce0133030c148ce"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
hash = "3ccb5713e745db48dfcb6174853161d8fed60ecbdf770dc78ae5663f5b04f352"
metafile = true

[[files]]
file = "mods/yosbr.pw.toml"
hash = "bbbcf529b4c35f04e733922ca06dde4aac8d97a556e4396da25d99e2d079c0c9"
metafile = true

[[files]]
file = "mods/zoomify.pw.toml"
hash = "c41c88bf75d26b2b5eda3254ebfef62a6e8625d75c2a80cfe1207c95b9de2c5f"
metafile = true

[[files]]
file = "resourcepacks/skyblocker modpack.zip"
hash = "26af891b19a7ec8f83a68b75a1cbf498b24a42cb5e3449cdef5ceead1438442c"

[[files]]
file = "servers.dat"
hash = "455f8e439d77c707f7c45a0b140000f3b8e70df252d0db1df390bf22e8a9b98e"

[[files]]
file = "servers.dat_old"
hash = "3d5552097b4529901567e0d6a27b490c4dfc7fdb7d2aaed597795894f1b881ce"
