name = "Skyblocker Modpack"
author = "Wohlhabend/LifeIsAParadox"
version = "3.5.7"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "aaaab2e255f08624d1db54dfc264b3dcc64f5c16d3ff93cb07b043e3165fd8ec"

[versions]
fabric = "0.18.2"
minecraft = "1.21.10"
