name = "Skyblocker Modpack"
author = "Wohlhabend/LifeIsAParadox"
version = "3.5.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "38b9d86954c762b21d11f2efe31ab3bb677c6e930f034a6093d2dc2b01b012ba"

[versions]
fabric = "0.17.2"
minecraft = "1.21.8"
