name = "Skyblocker Modpack"
author = "Wohlhabend/LifeIsAParadox"
version = "3.5.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ed98c447dcccb17663f825267306462fdc3e69e2e8fdfbc16dfda3e0e1a482d1"

[versions]
fabric = "0.17.2"
minecraft = "1.21.8"
