hash-format = "sha256"

[[files]]
file = "config/modrinth.index.json"
hash = "a0c5f3af0d0426f3559c999f1d8e7a834086da893deeaef96f6144cf0d574f2c"

[[files]]
file = "config/simple-modpack-update-checker.json"
hash = "70654b3963b70228b2aea7d34522a18b570015a1ad750d2095613f7fb600db3e"

[[files]]
file = "config/yosbr/config/aaron-mod.json"
hash = "d1d201d38031def0512f0eb225c8c8d70636633ba644234a82c1ccaf7d6e9436"

[[files]]
file = "config/yosbr/config/chatpatches.json"
hash = "99320d94b3df04257c8392075807ea73798c7ee1aac81bafcc289bfafa3399e2"

[[files]]
file = "config/yosbr/config/entityculling.json"
hash = "b147dcda724b6741b27a753e1b0c1e1c3107ea72eff993b02a9c42ce605bda7a"

[[files]]
file = "config/yosbr/config/fabric/indigo-renderer.properties"
hash = "a67cdf8a28612ffa77dfd39e29796e7dfe4e09fd0628e7bbc56c8df7f3a4703e"

[[files]]
file = "config/yosbr/config/ferritecore.mixin.properties"
hash = "a2091a291309db8920c8a80e913ed31c24c29687d8cd25ac18076ad85a90ddb8"

[[files]]
file = "config/yosbr/config/gammautils.json"
hash = "30811ed5e085051dee82d5dc74a78aa89564c243720ba23d6852e406a71a7dd8"

[[files]]
file = "config/yosbr/config/immediatelyfast.json"
hash = "0bcdd02d11dc35070f645fafe39cef59b6cff810372b5fb139001cdf5be57a16"

[[files]]
file = "config/yosbr/config/iris-excluded.json"
hash = "4d3264b58c502afaeca3f44e8d2db0843c54b8ba957afd21a2d450fe10dafefb"

[[files]]
file = "config/yosbr/config/iris.properties"
hash = "fd7b65ea92f171e2e91dc3ad7fda0bc87208006db22ada70f6e7db8e380062e5"

[[files]]
file = "config/yosbr/config/lithium.properties"
hash = "79348e4677fbd9474a18f772ecd271efebccdffed3a3f0bf2cc546e93d5c205a"

[[files]]
file = "config/yosbr/config/modelfix-client.json"
hash = "1f7d946ec7a12efbbe58cdeedc2ae767446e06e7ffed095c18482d5cc27a86a7"

[[files]]
file = "config/yosbr/config/modmenu.json"
hash = "3f1c59816df57677e6068961d823f8c5171e965e354774614c1a468eca00ed35"

[[files]]
file = "config/yosbr/config/roughlyenoughitems/collapsible.json5"
hash = "569d5b061e7a2f8011d95a5d4a8d8a8fa9f31cd4d25d8117a356d64df0030c0e"

[[files]]
file = "config/yosbr/config/roughlyenoughitems/config.json5"
hash = "bdd73d00987ffebc54b4f6cd6b6529500b42ed2e6c84821ba4d9aaefacf2bdf2"

[[files]]
file = "config/yosbr/config/roughlyenoughitems/favorites.json5"
hash = "459eda5b95f7897a261b2947478e2ebe1c6b48b0c9e3ec05d4b2977aa9e9c227"

[[files]]
file = "config/yosbr/config/roughlyenoughitems/pinyin.properties"
hash = "2299cb82a725cfccd0b443bd7dd59b6978e21edd9aaf0c19ec708d3a9e5abc95"

[[files]]
file = "config/yosbr/config/roughlyenoughitems/pinyin_double.properties"
hash = "dac7a306d1d9dd7cea6a45bb697f66acf14a705d9eca579f6f2573388d5d56c6"

[[files]]
file = "config/yosbr/config/skyblocker.json"
hash = "4652b57259fedfcf0f44375dd7f787779b64ed9ef38520154aae769aef11aef5"

[[files]]
file = "config/yosbr/config/skyblocker/hud_widgets.json"
hash = "050379a562eaf9c62553b95cba0bb197b5a5c6ac5afbc60178cfa6261aa186c2"

[[files]]
file = "config/yosbr/config/skyblocker/shortcuts.json"
hash = "8ae7bf63044f1fd8262959deaba95accce855e35a9d02132bc53c441f72aed7a"

[[files]]
file = "config/yosbr/config/skyblocker/speed_presets.json"
hash = "93f72fe810d9f752eb9c8890717ed0ca74c98939c671381aaa0fdb99cc6dae57"

[[files]]
file = "config/yosbr/config/skyblocker/status_bars.json"
hash = "c7c4729825151e338c88b30b4be9f2594fb87ba1dedaceaaa37b8a54f1c1e71a"

[[files]]
file = "config/yosbr/config/skyblocker/update_notifications.json"
hash = "a2dded0b9bc87b27c613c35766bdc090309b99de8fb3b219dd892753c58877a4"

[[files]]
file = "config/yosbr/config/sodium-extra-options.json"
hash = "3bc7a5bc42d8afa3785e79941650f6ec2cb0f895445883303ac1c644c652b8e7"

[[files]]
file = "config/yosbr/config/sodium-extra.properties"
hash = "ab259e2369fc503c0cd905ec9b57b5867f4dbd249edf7a2b52193b36ffbcdeab"

[[files]]
file = "config/yosbr/config/sodium-fingerprint.json"
hash = "a6a686b41ee84af7094051f2cebef4e1d322efd654fce32106d12ad8eba76d49"

[[files]]
file = "config/yosbr/config/sodium-mixins.properties"
hash = "35d3939d1bc306839c6ad538803288b3d2bc8a2dfed4948eae569d540d6b8058"

[[files]]
file = "config/yosbr/config/sodium-options.json"
hash = "592d14ea22405d4057e1ec1e04902a00fd9f6a623e385261c1e4e17cc78b03ab"

[[files]]
file = "config/yosbr/config/tooltipscroll.json"
hash = "45b54631b6da5b2fd5d8c826b0ad179d4b643ec991d627d6980c461805181e97"

[[files]]
file = "config/yosbr/config/yacl.json5"
hash = "1fa97dc3412ea64defd44952854637ba438bdd4a5a7c00728c9dd917e011d9f6"

[[files]]
file = "config/yosbr/config/zoomify.json"
hash = "a498f39b73d4e4107650cff8749f05dae8edab089f455bf882d27dda0311442d"

[[files]]
file = "config/yosbr/options.txt"
hash = "80aea453a4d1ebe90f433867c6dca8db9c3bdb921196276b18259c8b1a3b384b"

[[files]]
file = "mods/aaron-mod.pw.toml"
hash = "2df531e0d242ef958a22533745ee04d4a82ace666510bfde163c33b83a97f6f4"
metafile = true

[[files]]
file = "mods/architectury-api.pw.toml"
hash = "eff333c147ebe35865fe6bda43e334db1dc6d0769fdfb409dfb13a6037a2362e"
metafile = true

[[files]]
file = "mods/chatpatches.pw.toml"
hash = "745f22e8b829badfee2d670311d79477fa0de51e287781eea46159276841a168"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "47cb2d64a12e141e11ce5a211d9036a23c41698e3ea7de5dc8f4fd08638b2694"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "d3bbfa6dfe862010467f79ee37fb0dd51cf6bb8253d4b0fa1eb7d7f2f30e3801"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "0345fbfa8542b5ec84535fe2aff0f5cc4e801ecc337f926d4e2310b53f458569"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "61afd7af5c645ffd966b2bd86be944eacd1e48a8044e8f67082225d4d9989f0c"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "691cea763cfcd4625c3b7af109acba96289ade9cfe0008510f05dc4abf98eb50"
metafile = true

[[files]]
file = "mods/gamma-utils.pw.toml"
hash = "411d214608bc9689f9a3206ca475a3b2185c55efc52a18a0bd2d27d0e2bacb64"
metafile = true

[[files]]
file = "mods/immediatelyfast.pw.toml"
hash = "77364cc74f5c0819ef77e5e2fd11bd304ad98dc193348d3d875e23fae62f8f74"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
hash = "fecd2e19a6afd8109bb6cfc281d158e3f7a5d6646a99340e2ece5d1aaece4edc"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "45957cf6ae9def414ae6d1abcc91d97e054e8a3c59bf79f8a40644b9f8e0e09b"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "6f9c7fd82681111859ff63446dc8327447adeaad84e9cfb534955afb5eb6c81a"
metafile = true

[[files]]
file = "mods/placeholder-api.pw.toml"
hash = "da8027302e071db16b21c4abf1ab8f04245b283c4f44a3fdf98dc1e4c6d2d585"
metafile = true

[[files]]
file = "mods/reeses-sodium-options.pw.toml"
hash = "72e7bc0f4d9046648481488873cea91f6d4f5338cda67538c5317806ae71c5b9"
metafile = true

[[files]]
file = "mods/rei.pw.toml"
hash = "9906dacfff9777acb306b5e1f8e7d8e4a187a728e649d916839bf71b260b804a"
metafile = true

[[files]]
file = "mods/skyblocker-liap.pw.toml"
hash = "b2cfb566acf2b4a44ad6857457f1af4de86526da4860ec5c1cf94fe16b57f8ef"
metafile = true

[[files]]
file = "mods/skyblocker-modpack-lib-1.0.0.jar"
hash = "5972327b4f6d78d2bc8fc0696c7f0f2cd3a4c32e402d38c3c88996dece4338ef"

[[files]]
file = "mods/smuc.pw.toml"
hash = "88c6d9af0195942f70640c693b6ec173a9e9656782d51b3cbcc9e93305b0c7ab"
metafile = true

[[files]]
file = "mods/sodium-extra.pw.toml"
hash = "69f8726c1cf2e486d166a40dc253d01eade959d21b429cf7e7c413861a3c2ec0"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "7caca0627faddce5ea61f7e8ceadb4d5e63ca4cc661c2b810ac1a5e937fb3c29"
metafile = true

[[files]]
file = "mods/tooltip-scroll.pw.toml"
hash = "96a04da255138e04470dd65949c52a38787bda879082d006dff7605e397a3267"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
hash = "976682e613b79e310fe22c5ddc2322bfc76665295cd9fa885787dfa08b7764b2"
metafile = true

[[files]]
file = "mods/yosbr.pw.toml"
hash = "34d8808403d641935e0803cd2b83a33689cdb351d2614e990a2c9268958a6a19"
metafile = true

[[files]]
file = "mods/zoomify.pw.toml"
hash = "a75a40e1e61a074f8c0bc203254b325d7f251f22974fd82b0b3af1abb6ba818e"
metafile = true

[[files]]
file = "servers.dat"
hash = "455f8e439d77c707f7c45a0b140000f3b8e70df252d0db1df390bf22e8a9b98e"

[[files]]
file = "servers.dat_old"
hash = "3d5552097b4529901567e0d6a27b490c4dfc7fdb7d2aaed597795894f1b881ce"
