name = "Skyblocker Modpack"
author = "Wohlhabend/LifeIsAParadox"
version = "3.5.10"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "79d822dcf7d72113ea495661db24f109a6ffc6669625e508cad9d82c4acadb94"

[versions]
fabric = "0.18.4"
minecraft = "1.21.10"
